<a href="https://colab.research.google.com/github/JUERNES360/Biblioteca/blob/main/Laboratorio_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

data = {
  'Nombre': ['Ana','Luis','Carlos','Maria','Ernesto','Berta','Luisa','Angel'],
  'Profesion': ['Ama de casa','Ingeniero','Odontologo','Mecanico','Electricista','Abogado','Enfermera','Medico',],
  'Paises': ['Chile','Canada','Nicaragua','Portugal','Honduras','España','Colombia','Holanda']
}

df = pd.DataFrame(data)
print(df)

    Nombre     Profesion     Paises
0      Ana   Ama de casa      Chile
1     Luis     Ingeniero     Canada
2   Carlos    Odontologo  Nicaragua
3    Maria      Mecanico   Portugal
4  Ernesto  Electricista   Honduras
5    Berta       Abogado     España
6    Luisa     Enfermera   Colombia
7    Angel        Medico    Holanda


In [14]:
import pandas as pd
# cargar el archivo CSV que esta en la carpte comp
data = pd.read_json('data.json') #reemplaza 'nombre_del_archivo.csv' el nombre de tu archivo
print(df.head())

    Nombre     Profesion     Paises
0      Ana   Ama de casa      Chile
1     Luis     Ingeniero     Canada
2   Carlos    Odontologo  Nicaragua
3    Maria      Mecanico   Portugal
4  Ernesto  Electricista   Honduras


In [15]:
# Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios,
#y luego mostrar un resumen estadístico de los datos

import pandas as pd
import numpy as np #traer la libreria de numpy
df = pd.DataFrame(np.random.rand(100, 8))
print(df.describe())

                0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.530074    0.482395    0.478842    0.508263    0.591713    0.530998   
std      0.283723    0.287223    0.298922    0.273389    0.257941    0.264266   
min      0.027015    0.001108    0.003851    0.001708    0.051655    0.030180   
25%      0.323970    0.224736    0.198899    0.286720    0.406679    0.342910   
50%      0.512445    0.469737    0.523370    0.484767    0.578465    0.576703   
75%      0.777344    0.713958    0.734400    0.718477    0.820668    0.734817   
max      0.994898    0.972990    0.983607    0.985271    0.992403    0.990905   

                6           7  
count  100.000000  100.000000  
mean     0.492905    0.566898  
std      0.287741    0.284417  
min      0.009922    0.009697  
25%      0.239543    0.311523  
50%      0.495935    0.625464  
75%      0.734425    0.775617  
max      0.992

In [19]:
# Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.
import numpy as np
arr = np.arange(1,11)
print("Array:",arr)
print("Suma:",arr.sum())
print("Media:",arr.mean())
print("Maximo:",arr.max())



Array: [ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Maximo: 10


In [22]:
# Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6
import numpy as np
arr = np.zeros((3, 4))
print("Array original (3x4):")
print(arr)
print()
#camabiar la forma
arr = arr.reshape((2, 6))
print("Array despues de reshape (2x6):")
print(arr)

Array original (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array despues de reshape (2x6):
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
# Generar una matriz aleatoria de 3x3 y calcular su transpuesta.

import numpy as np
arr = np.random.rand(3, 3)
print("Matriz Original:")
print(arr)
print()
transpuesta = arr.T
print("Matriz Transpuesta:")
print(transpuesta)

Matriz Original:
[[0.47529715 0.15765634 0.13764156]
 [0.98426244 0.36101566 0.41702857]
 [0.88902295 0.7513846  0.64656147]]

Matriz Transpuesta:
[[0.47529715 0.98426244 0.88902295]
 [0.15765634 0.36101566 0.7513846 ]
 [0.13764156 0.41702857 0.64656147]]


In [26]:
# - Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el
# array concatenado. %%

import pandas as np
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
arr_concatenado = np.concatenate((a,b))
print("Array concatenado:",arr_concatenado)



Array concatenado: [ 1  2  3  4  5  6  7  8  9 10]
